paths:
  input_pdfs: "data/input_pdfs"
  input_images: "data/input_images"
  page_images: "data/page_images"
  output_json: "data/outputs/json"
  output_viz: "data/outputs/viz"
  models:
    signature: "models/signature/yolov8s.pt"
    stamp: "models/stamp/best.pt"
    qr: "models/qr/YOLOV8s_Barcode_Detection.pt"

inference:
  img_size: 1024          # для общей детекции
  img_size_stamp: 512     # для crop-детектора подписи (можешь 384/256 попробовать)

  conf_threshold:
    signature_global: 0.4   # подписи на всей странице
    signature_in_stamp: 0.1   # подписи внутри печатей
    stamp: 0.75
    qr: 0.25

  iou_nms:
    signature: 0.5
    stamp: 0.5
    qr: 0.5

  stamp_with_signature_iou: 0.2

classes_to_labels:   # если нужно маппить на label_XX
  signature: "signature"
  stamp: "stamp"
  qr: "qr"